### PR TITLE
Created contributors page

### PR DESCRIPTION
**Pull request by andreidolhescu**
Issue link here: https://github.com/nnetworth/nnetworth.com/issues/6

### CODE REVIEW

**Comment by kienpham2000** [comment]
thank you @andreidolhescu !

@kanishkarj Would merging this in conflict with your current branch? If not, this PR looks good to me to merge in!

**Comment by kienpham2000** [comment]
hi @andreidolhescu , now that @kanishkarj have merged in his initial work, would you please rebase and resolve conflict again? Thank you!

**Comment by andreidolhescu** [comment]
@kienpham2000 merge done

**Comment by kienpham2000** [comment]
Thank you @andreidolhescu !

**Comment by kienpham2000** [comment]
@andreidolhescu added you to our contributor group: https://github.com/nnetworth/nnetworth.com/invitations

**Pull request merged**
