### PR TITLE
Initiated Webpack Config with Vue js

### PR DESCRIPTION
**Pull request by kanishkarj**

### CODE REVIEW

**Comment by kienpham2000** [comment]
awesome work so far Kanishkar @kanishkarj . Thank you :)!

**Comment by kanishkarj** [comment]
@kienpham2000 Jquery and Vue js don't go well hand in hand. So I won't be able to apply all the styles and animations, as most of them are done with jquery. I shall try my best to replicate the project, but there will be differences. is that okay?

**Comment by kienpham2000** [comment]
@kanishkarj oh yea the template is pretty old, I like their UI, but if we can't port animation, I think it's cool. Thank you for your work so far, keep it up!

**Comment by kanishkarj** [comment]
@kienpham2000 ah cool! shall do as much as possible!

**Pull request merged**
